import type { ForestZoneKey } from './geo';

export type IncidentStatusSeed =
  | 'PENDING'
  | 'VIGILANCE'
  | 'ALERTE'
  | 'INTERVENTION'
  | 'MAITRISE'
  | 'ETEINT'
  | 'COMPLETED'
  | 'IN_PROGRESS';

export interface IncidentSeed {
  zoneKey: ForestZoneKey;
  cause: string;
  severity: number;
  status: IncidentStatusSeed;
  description: string;
  lang: 'fr' | 'ar';
  /** ISO date the incident started (createdAt). */
  createdAt: string;
  /** ISO date of last status change (updatedAt); defaults to createdAt. */
  updatedAt?: string;
  investigationStatus?: 'NOT_INVESTIGATED' | 'UNDER_INVESTIGATION' | 'CAUSE_DETERMINED' | 'INCONCLUSIVE';
  investigationNotes?: string;
  legalFollowUp?: boolean;
  /** Index into REPORTS (seed-data/reports.ts) whose citizen report triggered
   * this incident — set on both sides (Incident.reportId / Report.incidentId). */
  originReportIndex?: number;
  /** True for the 2-3 incidents that should be "live" for the demo map. */
  active?: boolean;
}

// 25 incidents across the 2026 campaign (June-September). Ordered roughly
// chronologically. The three `active: true` entries are the most recent,
// near Parc National d'Ifrane, for the live-map demo.
export const INCIDENTS: IncidentSeed[] = [
  {
    zoneKey: 'ajdirAzrou',
    cause: 'CAMPFIRE_UNATTENDED',
    severity: 2,
    status: 'ETEINT',
    lang: 'fr',
    description: "Feu de camp mal éteint retrouvé en lisière de la forêt d'Ajdir ; départ de feu limité, maîtrisé par une patrouille CEDEFO avant extension.",
    createdAt: '2026-06-03T10:15:00Z',
    updatedAt: '2026-06-03T13:40:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    originReportIndex: 0,
  },
  {
    zoneKey: 'tighboula',
    cause: 'CIGARETTE',
    severity: 1,
    status: 'ETEINT',
    lang: 'fr',
    description: 'Départ de feu de faible ampleur en bordure de piste à Tighboula, probablement causé par un mégot jeté depuis un véhicule.',
    createdAt: '2026-06-08T15:05:00Z',
    updatedAt: '2026-06-08T16:20:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'ainLeuhForest',
    cause: 'AGRICULTURAL_BURNING',
    severity: 3,
    status: 'ETEINT',
    lang: 'fr',
    description: "Écobuage agricole non maîtrisé ayant gagné la lisière forestière près d'Aïn Leuh ; intervention conjointe DPEFLCD / Protection Civile.",
    createdAt: '2026-06-12T12:30:00Z',
    updatedAt: '2026-06-12T17:10:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    originReportIndex: 1,
  },
  {
    zoneKey: 'timahditeForest',
    cause: 'ELECTRICAL',
    severity: 2,
    status: 'ETEINT',
    lang: 'fr',
    description: "Court-circuit sur une ligne moyenne tension en bordure de la forêt de Timahdite, foyer circonscrit rapidement.",
    createdAt: '2026-06-17T09:50:00Z',
    updatedAt: '2026-06-17T11:30:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'jbelHebri',
    cause: 'LIGHTNING',
    severity: 3,
    status: 'ETEINT',
    lang: 'ar',
    description: 'حريق ناجم عن صاعقة رعدية بمنطقة جبل هبري، تم التحكم فيه بعد تدخل فرق الوقاية المدنية والمياه والغابات.',
    createdAt: '2026-06-22T18:05:00Z',
    updatedAt: '2026-06-23T02:00:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'cedreGouraud',
    cause: 'CAMPFIRE_UNATTENDED',
    severity: 4,
    status: 'ETEINT',
    lang: 'fr',
    description: "Feu de bivouac abandonné dans la cédraie de Gouraud ayant embrasé la litière de cèdres sur un flanc pentu ; moyens aériens sollicités en renfort.",
    createdAt: '2026-06-28T13:20:00Z',
    updatedAt: '2026-06-29T09:00:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    legalFollowUp: false,
    originReportIndex: 2,
  },
  {
    zoneKey: 'tizguit',
    cause: 'UNKNOWN',
    severity: 2,
    status: 'ETEINT',
    lang: 'fr',
    description: 'Foyer de faible superficie détecté dans la vallée du Tizguit lors d\'une patrouille de routine ; cause non déterminée avec certitude.',
    createdAt: '2026-07-02T07:40:00Z',
    updatedAt: '2026-07-02T09:15:00Z',
    investigationStatus: 'INCONCLUSIVE',
  },
  {
    zoneKey: 'ainVittelForest',
    cause: 'CIGARETTE',
    severity: 1,
    status: 'ETEINT',
    lang: 'fr',
    description: "Petit départ de feu près des sources d'Aïn Vittel, zone très fréquentée par les visiteurs ; éteint avant propagation.",
    createdAt: '2026-07-05T14:10:00Z',
    updatedAt: '2026-07-05T14:55:00Z',
  },
  {
    zoneKey: 'michlifenSlopes',
    cause: 'ARSON',
    severity: 4,
    status: 'ETEINT',
    lang: 'fr',
    description: 'Départs de feux multiples et simultanés sur les versants du Michlifen — indices de malveillance relevés, enquête transmise au parquet.',
    createdAt: '2026-07-09T20:15:00Z',
    updatedAt: '2026-07-10T06:30:00Z',
    investigationStatus: 'UNDER_INVESTIGATION',
    investigationNotes: "Traces d'accélérant relevées en trois points distincts ; procès-verbal transmis à la Gendarmerie Royale.",
    legalFollowUp: true,
    originReportIndex: 3,
  },
  {
    zoneKey: 'parcCentral',
    cause: 'LIGHTNING',
    severity: 5,
    status: 'ETEINT',
    lang: 'fr',
    description: "Incendie majeur déclenché par la foudre au cœur du Parc National d'Ifrane pendant un épisode orageux sec ; moyens aériens et renfort mutuel Fès-Meknès engagés.",
    createdAt: '2026-07-14T11:30:00Z',
    updatedAt: '2026-07-15T08:00:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'ajdirAzrou',
    cause: 'EQUIPMENT_MALFUNCTION',
    severity: 2,
    status: 'ETEINT',
    lang: 'fr',
    description: "Étincelle provenant d'une débroussailleuse thermique ayant enflammé des broussailles sèches près d'Ajdir.",
    createdAt: '2026-07-18T10:00:00Z',
    updatedAt: '2026-07-18T11:40:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'tighboula',
    cause: 'AGRICULTURAL_BURNING',
    severity: 3,
    status: 'MAITRISE',
    lang: 'fr',
    description: "Brûlage de chaume ayant échappé à son périmètre à Tighboula ; feu circonscrit mais surveillance renforcée sur les points chauds résiduels.",
    createdAt: '2026-07-22T13:45:00Z',
    updatedAt: '2026-07-22T18:00:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    originReportIndex: 4,
  },
  {
    zoneKey: 'jbelHebri',
    cause: 'CIGARETTE',
    severity: 2,
    status: 'ETEINT',
    lang: 'ar',
    description: 'حريق صغير قرب المسلك الغابوي بجبل هبري، السبب المرجح عقب سيجارة مرمية من سيارة عابرة.',
    createdAt: '2026-07-26T16:30:00Z',
    updatedAt: '2026-07-26T17:50:00Z',
  },
  {
    zoneKey: 'ainLeuhForest',
    cause: 'ARSON',
    severity: 3,
    status: 'ETEINT',
    lang: 'fr',
    description: "Départ de feu suspect en trois foyers distincts près d'Aïn Leuh ; enquête ouverte, aucune interpellation à ce jour.",
    createdAt: '2026-07-30T21:10:00Z',
    updatedAt: '2026-07-31T05:00:00Z',
    investigationStatus: 'UNDER_INVESTIGATION',
    legalFollowUp: true,
  },
  {
    zoneKey: 'cedreGouraud',
    cause: 'LIGHTNING',
    severity: 3,
    status: 'ETEINT',
    lang: 'fr',
    description: 'Impact de foudre isolé dans la cédraie de Gouraud, feu de sous-bois circonscrit avant la tombée de la nuit.',
    createdAt: '2026-08-03T17:20:00Z',
    updatedAt: '2026-08-03T20:45:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'timahditeForest',
    cause: 'OTHER',
    severity: 2,
    status: 'ETEINT',
    lang: 'fr',
    description: "Feu accidentel lié à des travaux de soudure sur une clôture agricole en bordure de la forêt de Timahdite.",
    createdAt: '2026-08-07T09:15:00Z',
    updatedAt: '2026-08-07T10:50:00Z',
  },
  {
    zoneKey: 'parcCentral',
    cause: 'CAMPFIRE_UNATTENDED',
    severity: 3,
    status: 'MAITRISE',
    lang: 'fr',
    description: "Feu de campement de vacanciers non éteint dans le Parc National, repris par le vent en début de soirée ; en cours de stabilisation.",
    createdAt: '2026-08-11T19:00:00Z',
    updatedAt: '2026-08-11T23:30:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    originReportIndex: 5,
  },
  {
    zoneKey: 'ainVittelForest',
    cause: 'UNKNOWN',
    severity: 1,
    status: 'PENDING',
    lang: 'fr',
    description: "Signalement d'odeur de fumée près d'Aïn Vittel, patrouille de vérification programmée — non confirmé sur place à ce stade.",
    createdAt: '2026-08-14T08:05:00Z',
    investigationStatus: 'NOT_INVESTIGATED',
  },
  {
    zoneKey: 'jbelHebri',
    cause: 'LIGHTNING',
    severity: 4,
    status: 'IN_PROGRESS',
    lang: 'fr',
    description: "Foyer déclenché par la foudre sur le versant nord de Jbel Hebri, progression ralentie par la tranchée pare-feu ; opération toujours en cours de finalisation administrative.",
    createdAt: '2026-08-18T15:40:00Z',
    updatedAt: '2026-08-19T07:00:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
  },
  {
    zoneKey: 'ajdirAzrou',
    cause: 'AGRICULTURAL_BURNING',
    severity: 2,
    status: 'ETEINT',
    lang: 'fr',
    description: "Brûlage agricole non déclaré à proximité d'Ajdir, feu de faible ampleur rapidement circonscrit.",
    createdAt: '2026-08-21T11:25:00Z',
    updatedAt: '2026-08-21T12:40:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    originReportIndex: 6,
  },
  {
    zoneKey: 'tizguit',
    cause: 'CIGARETTE',
    severity: 1,
    status: 'COMPLETED',
    lang: 'ar',
    description: 'حريق طفيف بوادي تيزكيت، تم إخماده من طرف فرقة دورية قبل وصول الدعم.',
    createdAt: '2026-08-25T13:00:00Z',
    updatedAt: '2026-08-25T13:35:00Z',
  },
  {
    zoneKey: 'michlifenSlopes',
    cause: 'EQUIPMENT_MALFUNCTION',
    severity: 2,
    status: 'VIGILANCE',
    lang: 'fr',
    description: "Point chaud résiduel détecté par imagerie satellite FIRMS sur les versants du Michlifen, sous surveillance rapprochée sans intervention lourde.",
    createdAt: '2026-09-01T06:30:00Z',
    investigationStatus: 'NOT_INVESTIGATED',
    originReportIndex: 7,
  },
  {
    zoneKey: 'ainLeuhForest',
    cause: 'OTHER',
    severity: 2,
    status: 'VIGILANCE',
    lang: 'fr',
    description: "Fumée diffuse signalée par des promeneurs près d'Aïn Leuh ; secteur classé en vigilance renforcée compte tenu de l'indice de risque élevé.",
    createdAt: '2026-09-06T16:15:00Z',
    investigationStatus: 'NOT_INVESTIGATED',
    originReportIndex: 8,
  },
  // ── Active incidents for the live demo map (most recent, near the park) ──
  {
    zoneKey: 'parcCentral',
    cause: 'CAMPFIRE_UNATTENDED',
    severity: 4,
    status: 'INTERVENTION',
    lang: 'fr',
    description: "Feu de camp non maîtrisé au cœur du Parc National d'Ifrane, propagation active vers le nord poussée par un vent soutenu ; trois équipes au sol et appui aérien engagés.",
    createdAt: '2026-09-23T14:05:00Z',
    updatedAt: '2026-09-24T07:30:00Z',
    investigationStatus: 'UNDER_INVESTIGATION',
    active: true,
    originReportIndex: 9,
  },
  {
    zoneKey: 'cedreGouraud',
    cause: 'LIGHTNING',
    severity: 5,
    status: 'INTERVENTION',
    lang: 'fr',
    description: "Incendie de cime dans la cédraie de Gouraud consécutif à un impact de foudre nocturne ; POI 2 activé, renfort mutuel demandé à la province de Meknès.",
    createdAt: '2026-09-24T02:10:00Z',
    updatedAt: '2026-09-24T09:15:00Z',
    investigationStatus: 'CAUSE_DETERMINED',
    active: true,
  },
  {
    zoneKey: 'jbelHebri',
    cause: 'UNKNOWN',
    severity: 3,
    status: 'ALERTE',
    lang: 'fr',
    description: "Départ de fumée confirmé par le poste vigie de Jbel Hebri en fin de matinée ; équipe de reconnaissance en approche, alerte maintenue en l'absence de confirmation visuelle des flammes.",
    createdAt: '2026-09-24T10:45:00Z',
    investigationStatus: 'NOT_INVESTIGATED',
    active: true,
  },
];
